language: csharp
solution: naija-cover.sln
mono:
 - latest
install:
  - wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore NETCover.sln
script:
  - xbuild /p:Configuration=Release NETCover.sln