language: csharp
solution: naija-cover.sln
mono:
 - latest
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore naija-cover.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release naija-cover.sln